---@class Language アバターの表示言語を管理するクラス
---@field Language.LanguageData table 言語データ

Language = {
	LanguageData = {
		en_us = {
			language__en_us = "English",
			language__ja_jp = "Japanese",
			key_name__wag_tail = "Wag tail",
			key_name__jerk_ears = "Jerk ears",
			costume__default = "Default costume",
			costume__nightwear = "Nightwear",
			costume__disguise = "Going out costume",
			costume__maid_a = "Maid costume A",
			costume__maid_b = "Maid costume B",
			costume__swimsuit = "Swimsuit",
			costume__cheerleader = "Cheerleader costume",
			costume__purification = "Purification clothes",
			costume__kappogi = "Kappogi (cook's apron)",
			costume__yukata = "Yukata",
			costume__knit = "Knitted hat",
			costume__fox_hoodie_red = "Fox hoodie (red)",
			costume__fox_hoodie_white = "Fox hoodie (white)",
			costume__tracksuit = "Tracksuit",
			costume__casual = "Casual clothes",
			costume__sailor = "Sailor suit",
			costume__china_dress = "China dress",
			costume__santa = "Santa costume",
			costume__kimono = "Kimono",
			skull__default = "Default",
			skull__figure_a = "Figure",
			skull__figure_b = "Maid Figure",
			skull__figure_c = "Cheerleader Figure",
			skull__figure_d = "Fox hoodie Figure",
			action_wheel__toggle_off = "§coff",
			action_wheel__toggle_on = "§aon",
			action_wheel__refuse_action = "(It is not the time... I have a strong feeling bad sign...)",
			action_wheel__close_to_confirm = "(Close action wheel to confirm.)",
			action_wheel__main__action_8__title = "Change pages §7(scroll)§r: §b",
			action_wheel__main_1__title = "Standing actions",
			action_wheel__main_1__action_1__title = "Uyan♪",
			action_wheel__main_1__action_2__title = "Body shake",
			action_wheel__main_1__action_2__unavailable = "I cannot do body shake now.",
			action_wheel__main_1__action_3__title = "Broom cleaning",
			action_wheel__main_1__action_3__unavailable = "I cannot clean now.",
			action_wheel__main_1__action_4__title = "Hair cut",
			action_wheel__main_1__action_4__unavailable = "I cannot give you a haircut now.",
			action_wheel__main_1__action_5__title = "Fox jump",
			action_wheel__main_1__action_5__unavailable = "I cannot jump here.",
			action_wheel__main_1__action_6__title = "Tail brushing",
			action_wheel__main_1__action_6__unavailable = "I cannot brush my tail now.",
			action_wheel__main_1__action_7__title = "Kotatsu",
			action_wheel__main_1__action_7__unavailable = "I cannot feel at home now.",
			action_wheel__main_1__action_7__start = "Loosely",
			action_wheel__main_2__title = "Sitting actions",
			action_wheel__main_2__action_1__title = "Sit down",
			action_wheel__main_2__action_1__unavailable = "I cannot sit down now.",
			action_wheel__main_2__action_2__title = "Cuddle tail",
			action_wheel__main_2__action_2__unavailable = "I cannot let you cuddle now.",
			action_wheel__main_2__action_3__title = "Cuddle ears",
			action_wheel__main_2__action_3__unavailable = "I cannot let you cuddle now.",
			action_wheel__main_2__action_4__title = "Earpick",
			action_wheel__main_2__action_4__unavailable = "I will clean your ears after I sit down!",
			action_wheel__main_2__action_5__title = "Tea time",
			action_wheel__main_2__action_5__unavailable = "I will sip tea after I sit down!",
			action_wheel__main_2__action_6__title = "Massage",
			action_wheel__main_2__action_6__unavailable = "I will massage you after I sit down!",
			action_wheel__main_3__title = "Photo pose",
			action_wheel__main_3__action_1__title = "Photo pose 1",
			action_wheel__main_3__action_2__title = "Photo pose 2",
			action_wheel__main_3__action__unavailable = "I cannot pose now.",
			action_wheel__main_4__title = "Avatar config 1",
			action_wheel__main_4__action_1__title = "What costume should I wear? §7(scroll)§r: ",
			action_wheel__main_4__action_1__done_first = "I changed my clothers to §b",
			action_wheel__main_4__action_1__done_last = "§r!",
			action_wheel__main_4__action_2__title = "What should I be called? §7(scroll)§r: ",
			action_wheel__main_4__action_2__done_first = "I changed my name to §b",
			action_wheel__main_4__action_2__done_last = "§r!",
			action_wheel__main_4__action_3__title = "What types of my head block should I choose? §7(scroll)§r: ",
			action_wheel__main_4__action_3__done_first = "I changed my head block to §b",
			action_wheel__main_4__action_3__done_last = "§r!",
			action_wheel__main_4__action_4__title = "Auto shake: ",
			action_wheel__main_4__action_5__title = "Show armor: ",
			action_wheel__main_4__action_6__title = "Show fox fire in first person: ",
			action_wheel__main_4__action_7__title = "Umbrella sound: ",
			action_wheel__main_5__title = "Avatar config 2",
			action_wheel__main_5__action_1__title = "Always use umbrella: ",
			message__afk_too_long = "You! Whre have you been? Possibly, you might have been cuddling other fluffy things even you have me, a fox... sigh... You mean you aren't satisfied even you always cuddle me ...",
			message__merry_christmas = "Merry Christmas!"
		},
		ja_jp = {
			language__en_us = "英語",
			language__ja_jp = "日本語",
			key_name__wag_tail = "尻尾ふりふり",
			key_name__jerk_ears = "お耳ぴくぴく",
			costume__default = "いつもの服",
			costume__nightwear = "寝間着",
			costume__disguise = "お出かけ服",
			costume__maid_a = "めいど服A",
			costume__maid_b = "めいど服B",
			costume__swimsuit = "水着",
			costume__cheerleader = "ちありーだーの服",
			costume__purification = "清めの服",
			costume__kappogi = "割烹着",
			costume__yukata = "浴衣",
			costume__knit = "にっと帽",
			costume__fox_hoodie_red = "きつねぱーかー（赤）",
			costume__fox_hoodie_white = "きつねぱーかー（白）",
			costume__tracksuit = "じゃーじ",
			costume__casual = "かじゅあるな服",
			costume__sailor = "せーらー服",
			costume__china_dress = "ちゃいなどれす",
			costume__santa = "さんたさんの服",
			costume__kimono = "着物",
			skull__default = "でふぉると",
			skull__figure_a = "ふぃぎゅあ",
			skull__figure_b = "めいどのふぃぎゅあ",
			skull__figure_c = "ちありーだーのふぃぎゅあ",
			skull__figure_d = "きつねぱーかーのふぃぎゅあ",
			action_wheel__toggle_off = "§cおふ",
			action_wheel__toggle_on = "§aおん",
			action_wheel__refuse_action = "（今はそれどころじゃないのじゃ...何かよからぬ気配を強く感じるのじゃ...）",
			action_wheel__close_to_confirm = "（あくしょんほいーるを閉じて確定なのじゃ。）",
			action_wheel__main__action_8__title = "ぺーじ切り替え§7（すくろーる）§r：§b",
			action_wheel__main_1__title = "立ちあくしょん",
			action_wheel__main_1__action_1__title = "うやん♪",
			action_wheel__main_1__action_2__title = "ぶるぶる",
			action_wheel__main_1__action_2__unavailable = "今はぶるぶるできないのじゃ。",
			action_wheel__main_1__action_3__title = "お掃除",
			action_wheel__main_1__action_3__unavailable = "今は掃除できないのじゃ。",
			action_wheel__main_1__action_4__title = "散髪",
			action_wheel__main_1__action_4__unavailable = "今は髪を切ってあげられないのじゃ。",
			action_wheel__main_1__action_5__title = "きつねじゃんぷ",
			action_wheel__main_1__action_5__unavailable = "ここでは跳べないのじゃ。",
			action_wheel__main_1__action_6__title = "尻尾の手入れ",
			action_wheel__main_1__action_6__unavailable = "今は手入れできないのじゃ。",
			action_wheel__main_1__action_7__title = "こたつ",
			action_wheel__main_1__action_7__unavailable = "今はだらーんできないのじゃ。",
			action_wheel__main_1__action_7__start = "だら～ん",
			action_wheel__main_2__title = "座りあくしょん",
			action_wheel__main_2__action_1__title = "おすわり",
			action_wheel__main_2__action_1__unavailable = "今は座れないのじゃ。",
			action_wheel__main_2__action_2__title = "尻尾もふもふ",
			action_wheel__main_2__action_2__unavailable = "今はもふもふしてあげられないのじゃ。",
			action_wheel__main_2__action_3__title = "お耳もふもふ",
			action_wheel__main_2__action_3__unavailable = "今はもふもふしてあげられないのじゃ。",
			action_wheel__main_2__action_4__title = "耳かき",
			action_wheel__main_2__action_4__unavailable = "座ってから耳かきをするかのう。",
			action_wheel__main_2__action_5__title = "お茶",
			action_wheel__main_2__action_5__unavailable = "座ってからお茶をすすろうかのう。",
			action_wheel__main_2__action_6__title = "まっさーじ",
			action_wheel__main_2__action_6__unavailable = "座ってからお主をほぐそうかのう。",
			action_wheel__main_3__title = "撮影ぽーず",
			action_wheel__main_3__action_1__title = "撮影ぽーず1",
			action_wheel__main_3__action_2__title = "撮影ぽーず2",
			action_wheel__main_3__action__unavailable = "今はぽーずをとれないのじゃ。",
			action_wheel__main_4__title = "あばたー設定1",
			action_wheel__main_4__action_1__title = "わらわは何を着ればよいのじゃ？§7（すくろーる）§r：",
			action_wheel__main_4__action_1__done_first = "§b",
			action_wheel__main_4__action_1__done_last = "§rに着替えたのじゃ。",
			action_wheel__main_4__action_2__title = "わらわは何と呼ばれればよいのじゃ？§7（すくろーる）§r: ",
			action_wheel__main_4__action_2__done_first = "わらわの呼び名を§b",
			action_wheel__main_4__action_2__done_last = "§rに変更したのじゃ。",
			action_wheel__main_4__action_3__title = "わらわの頭ぶろっくはどれがよいのじゃ？§7（すくろーる）§r: ",
			action_wheel__main_4__action_3__done_first = "わらわの頭ぶろっくを§b",
			action_wheel__main_4__action_3__done_last = "§rに変更したのじゃ。",
			action_wheel__main_4__action_4__title = "自動ぶるぶる：",
			action_wheel__main_4__action_5__title = "防具の表示：",
			action_wheel__main_4__action_6__title = "一人称視点での狐火の表示：",
			action_wheel__main_4__action_7__title = "傘の開閉音：",
			action_wheel__main_5__title = "あばたー設定2",
			action_wheel__main_5__action_1__title = "傘を常にさす：",
			message__afk_too_long = "お主！わらわを放ってどこに行ってたのじゃ！？もしや、お主、わらわという狐がありながら、またよそのもふもふにうつつを抜かしよったのか...。はぁ...、普段からあれだけもふっておきながら、まだ足りんと言うのか、お主は...。",
			message__merry_christmas = "めりーくりすますなのじゃ！"
		}
	},

	---翻訳キーに対する訳文を返す。設定言語が存在しない場合は英語の文が返される。また、指定したキーの訳が無い場合は英語->キーそのままが返される。
	---@param keyName string 翻訳キー
	---@return string translatedString 翻訳キーに対する翻訳データ。設定言語での翻訳が存在しない場合は英文が返される。英文すら存在しない場合は翻訳キーがそのまま返される。
	getTranslate = function(keyName)
		local activeLanguage = client:getActiveLang()
		return (Language.LanguageData[activeLanguage] and Language.LanguageData[activeLanguage][keyName]) and Language.LanguageData[activeLanguage][keyName] or (Language.LanguageData["en_us"][keyName] and Language.LanguageData["en_us"][keyName] or keyName)
	end,

	---利用可能な言語リストを返す。
	getLanguages = function()
		local result = {}
		for languageName, _ in pairs(Language.LanguageData) do
			table.insert(result, languageName)
		end
		return result
	end
}

return Language